# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='isOutstanding',
            field=models.BooleanField(default=True),
        ),
    ]
